import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { slateTheme, violetTheme } from "./actions/theme";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Form Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
